import numpy as np
import re

def readcoords(filename = None, convert = False):

    """
    read standard xyz file and convert all coordinates into float data type (optional).\n
    # Input requirement\n
    filename: string\n
    convert: bool\n
    # Output description\n
    2-dimensional list, may contain element symbol in the first column, but must contain 3-dimensional coordinates in last 3 column.
    """
    coords_inp = []
    print('COORD| coordinates read-in function is activated. Parsing file: '+filename)
    if filename == None:
        print('COORD| ***error*** no coordinate file is read, program is terminated.')
        exit()

    fileTag = open(filename, 'r', encoding='utf-8')
    print('COORD| the first two lines in *.xyz file will be omitted. Although it may be a\n'
         +'       good way to check completeness of file.')

    lineskip = 2
    iline = fileTag.readline()
    lineind = 1
    while iline:
        if lineind>lineskip:
            fragments = re.split(' |\n', iline)
            words = [word for word in fragments if word != '']
            coords_inp.append(words)
        
        iline = fileTag.readline()
        lineind += 1

    fileTag.close()
    if len(coords_inp) == 0:
        print('COORD| ***error*** there is no valid atomic information in *.xyz file, please check your file. QUIT.')
        exit()
    
    if convert:
        print('COORD| read-in complete, converting coordinates from str to float. Here atoms will be counted.')
        coordShape = np.shape(coords_inp)
        print('COORD| there are '+str(coordShape[0])+' atoms in total.')

        for iatom in range(coordShape[0]):
            for iaxis in range(1,4):
                coords_inp[iatom][iaxis] = float(coords_inp[iatom][iaxis])
        
        print('COORD| conversion complete.')
    
    else:
        print('COORD| read-in complete, remember that convert data from str to float-type for future use.')

    return coords_inp

def writecoords(coordlist, projectname = 'simu_pkg'):

    """
    output coordinates to external standard formatted xyz file.\n
    # input requirement\n
    coordlist: 2-dimensional list in the format of output of function readcoords\n
    projectname: any string that will be prefix of xyz file\n
    full filename output: projectname-pos-out.xyz\n
    """
    natom = np.shape(coordlist)[0]

    if np.shape(coordlist)[1] == 3:

        print('COORD| ***warning*** 3 column-atomic coordinates list detected! Please make sure that it'
             +'      is what you want. A raw will be printed out for check:')
        print(coordlist[0])
        ifquit = input('COORD| ***warning*** you can decide now if quit program. (y/n)')

        if ifquit == 'y':

            exit()
            print('COORD| ***error*** program quit from CoordWrite subroutine.')

        else:

            print('COORD| ***warning*** program will proceed continuely. Coordinates will be treated as'
                 +'      single-element, element symbol you need to input...')
            element = input('COORD| ***warning*** waiting for an element symbol input, all elements are supported.')

            if element:

                coordoutput = []
                for i in range(natom):

                    line = coordlist[i][:]
                    line.insert(0, element)
                    coordoutput.append(line)
    
    elif np.shape(coordlist)[1] == 4:

        coordoutput = coordlist

    else:

        print('COORD| ***error*** bad input format. program stoppted at CoordWrite routine. quit.')
        exit()

    print('COORD| write coordinates to file. name after '+str(projectname)+' , standard xyz file(s) output.')

    filename = projectname+'-pos-out.xyz'
    filetag = open(filename, 'a+', encoding='utf-8')

    filetag.writelines(str(natom)+'\n')
    filetag.writelines('Generated by simu_pkg coordWrite routine.\n')
    for iline in range(natom):

        filetag.writelines(
            "%3.3s"%coordoutput[iline][0]+' '
            +"%20.10f"%coordoutput[iline][1]
            +"%20.10f"%coordoutput[iline][2]
            +"%20.10f"%coordoutput[iline][3]
            +'\n'
            )
    
    filetag.close()

